# coding: utf-8

"""
    Middleware

    Knowledge Graph data management.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from middleware_client.api.autocomplete_api import AutocompleteApi


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutocompleteApi()

    def tearDown(self) -> None:
        pass

    def test_get(self) -> None:
        """Test case for get

        Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
